# [START django_app]
runtime: python37
entrypoint: exec gunicorn -b :$PORT timeCard.wsgi

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgres+pg8000://USER:saharacat@/sahara?unix_socket=/cloudsql/sahara-cat:asia-east2:sahara-cat

