# Generated by Django 3.0.2 on 2020-03-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testReact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='TestTbl',
        ),
    ]
